In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn import metrics as sm

In [29]:
df=pd.read_csv(r"C:\Users\Sangeeth Kumar\ML_Code_Files\airline_passenger_satisfaction_data\train.csv")

In [31]:
df.head(5)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [37]:
df.columns

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [49]:
df.shape

(103594, 23)

In [35]:
df.drop(["Unnamed: 0", "id"], axis = 1, inplace = True)

In [47]:
df.isna().sum()* 100 / len(df)

Gender                               0.0
Customer Type                        0.0
Age                                  0.0
Type of Travel                       0.0
Class                                0.0
Flight Distance                      0.0
Inflight wifi service                0.0
Departure/Arrival time convenient    0.0
Ease of Online booking               0.0
Gate location                        0.0
Food and drink                       0.0
Online boarding                      0.0
Seat comfort                         0.0
Inflight entertainment               0.0
On-board service                     0.0
Leg room service                     0.0
Baggage handling                     0.0
Checkin service                      0.0
Inflight service                     0.0
Cleanliness                          0.0
Departure Delay in Minutes           0.0
Arrival Delay in Minutes             0.0
satisfaction                         0.0
dtype: float64

In [45]:
df.dropna(inplace = True)

In [53]:

d = {"Business" : 3, "Eco Plus" : 2, "Eco" : 1}
df['Class'] = df['Class'].map(d)
df['Class'].unique()

array([2, 3, 1], dtype=int64)

In [59]:
d = {"neutral or dissatisfied" : 0, "satisfied" : 1}
df['satisfaction'] = df['satisfaction'].map(d)
df['satisfaction'].unique()

array([0, 1], dtype=int64)

In [61]:
df.head()

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,Male,Loyal Customer,13,Personal Travel,2,460,3,4,3,1,...,5,4,3,4,4,5,5,25,18.0,0
1,Male,disloyal Customer,25,Business travel,3,235,3,2,3,3,...,1,1,5,3,1,4,1,1,6.0,0
2,Female,Loyal Customer,26,Business travel,3,1142,2,2,2,2,...,5,4,3,4,4,4,5,0,0.0,1
3,Female,Loyal Customer,25,Business travel,3,562,2,5,5,5,...,2,2,5,3,1,4,2,11,9.0,0
4,Male,Loyal Customer,61,Business travel,3,214,3,3,3,3,...,3,3,4,4,3,3,3,0,0.0,1

In [71]:
df.select_dtypes(include = "number").columns

Index(['Gender_Female', 'Gender_Male', 'Customer Type_Loyal Customer',
       'Customer Type_disloyal Customer', 'Type of Travel_Business travel',
       'Type of Travel_Personal Travel'],
      dtype='object')

In [69]:
df = pd.get_dummies(df, columns = ['Gender', 'Customer Type', 'Type of Travel'])
df.head(2)

,Age,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel
0,13,2,460,3,4,3,1,5,3,5,...,5,25,18.0,0,False,True,True,False,False,True
1,25,3,235,3,2,3,3,1,3,1,...,1,1,6.0,0,False,True,False,True,True,False

In [73]:
Y = df['satisfaction']
X = df.loc[:, df.columns != "satisfaction"]

In [77]:
X_train, X_test, y_train, y_test  = train_test_split(X, Y, test_size = 0.2, random_state = 77)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((82875, 25), (20719, 25), (82875,), (20719,))

__Decision Tree to predict Customer Satisfacation__

In [79]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [85]:
DT = DecisionTreeClassifier(class_weight = "balanced")
DT.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced')

In [95]:
test_predictions = DT.predict(X_test)
train_predictions = DT.predict(X_train)

In [89]:
test_predictions

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [97]:
print(confusion_matrix(y_test, test_predictions))
print(classification_report(y_test, test_predictions))

print(confusion_matrix(y_train, train_predictions))
print(classification_report(y_train, train_predictions))

[[11119   569]
 [  605  8426]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95     11688
           1       0.94      0.93      0.93      9031

    accuracy                           0.94     20719
   macro avg       0.94      0.94      0.94     20719
weighted avg       0.94      0.94      0.94     20719

[[47009     0]
 [    0 35866]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     47009
           1       1.00      1.00      1.00     35866

    accuracy                           1.00     82875
   macro avg       1.00      1.00      1.00     82875
weighted avg       1.00      1.00      1.00     82875

__Random Forest Classifier__

In [101]:
RF = RandomForestClassifier(n_estimators = 99, class_weight= "balanced")
RF.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=99)

In [103]:
test_predictions = RF.predict(X_test)
train_predictions = RF.predict(X_train)

In [105]:
print(confusion_matrix(y_test, test_predictions))
print(classification_report(y_test, test_predictions))

print(confusion_matrix(y_train, train_predictions))
print(classification_report(y_train, train_predictions))

[[11453   235]
 [  548  8483]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.97     11688
           1       0.97      0.94      0.96      9031

    accuracy                           0.96     20719
   macro avg       0.96      0.96      0.96     20719
weighted avg       0.96      0.96      0.96     20719

[[47009     0]
 [    1 35865]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     47009
           1       1.00      1.00      1.00     35866

    accuracy                           1.00     82875
   macro avg       1.00      1.00      1.00     82875
weighted avg       1.00      1.00      1.00     82875